<a href="https://colab.research.google.com/github/arasulo/arasulo/blob/main/Bolean_indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [8]:
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javoxir', 'Elyor'])


In [9]:
data = np.random.randn (7, 4)
data

array([[ 0.20253616,  1.65547602,  0.62553916,  0.12100184],
       [ 0.38005663,  0.71606429,  0.73144474,  1.58502893],
       [ 0.6164023 ,  0.55275653,  0.14077322,  0.97602014],
       [-1.19930421, -0.52934677, -0.41657463, -0.57377711],
       [ 0.73513988,  0.35892349,  1.7969976 , -0.25398094],
       [ 0.43140327,  1.07638148, -0.89801104, -2.97617451],
       [ 0.50152535, -1.06255397,  0.37606069,  0.38831625]])

In [10]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [19]:
data[names == 'Husan']

array([[0.38005663, 0.71606429, 0.73144474, 1.58502893]])

data[names == 'Elyor']

In [21]:
data[names == 'Mirzabek']

array([[0.6164023 , 0.55275653, 0.14077322, 0.97602014]])

In [23]:
data[names == 'Javoxir']

array([[ 0.43140327,  1.07638148, -0.89801104, -2.97617451]])

In [24]:
data[names != 'Hasan']# Hasandan tashqari barcha malumotlarni ajratib olish

array([[ 0.38005663,  0.71606429,  0.73144474,  1.58502893],
       [ 0.6164023 ,  0.55275653,  0.14077322,  0.97602014],
       [-1.19930421, -0.52934677, -0.41657463, -0.57377711],
       [ 0.43140327,  1.07638148, -0.89801104, -2.97617451],
       [ 0.50152535, -1.06255397,  0.37606069,  0.38831625]])

In [25]:
print (names)
print (data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javoxir' 'Elyor']
[[ 0.20253616  1.65547602  0.62553916  0.12100184]
 [ 0.38005663  0.71606429  0.73144474  1.58502893]
 [ 0.6164023   0.55275653  0.14077322  0.97602014]
 [-1.19930421 -0.52934677 -0.41657463 -0.57377711]
 [ 0.73513988  0.35892349  1.7969976  -0.25398094]
 [ 0.43140327  1.07638148 -0.89801104 -2.97617451]
 [ 0.50152535 -1.06255397  0.37606069  0.38831625]]


In [26]:
data[~(names == 'Hasan')]# yuqoridagi cell kabi bir xil natijani beradi

array([[ 0.38005663,  0.71606429,  0.73144474,  1.58502893],
       [ 0.6164023 ,  0.55275653,  0.14077322,  0.97602014],
       [-1.19930421, -0.52934677, -0.41657463, -0.57377711],
       [ 0.43140327,  1.07638148, -0.89801104, -2.97617451],
       [ 0.50152535, -1.06255397,  0.37606069,  0.38831625]])

In [27]:
mask = (names == 'Hasan') | (names == 'Husan') # " | " or yoki
mask

array([ True,  True, False, False,  True, False, False])

In [28]:
data [mask]# Hasan va Husanlarga tegishli ma'lumotlarni ajratib oladi MB

array([[ 0.20253616,  1.65547602,  0.62553916,  0.12100184],
       [ 0.38005663,  0.71606429,  0.73144474,  1.58502893],
       [ 0.73513988,  0.35892349,  1.7969976 , -0.25398094]])

In [29]:
data

array([[ 0.20253616,  1.65547602,  0.62553916,  0.12100184],
       [ 0.38005663,  0.71606429,  0.73144474,  1.58502893],
       [ 0.6164023 ,  0.55275653,  0.14077322,  0.97602014],
       [-1.19930421, -0.52934677, -0.41657463, -0.57377711],
       [ 0.73513988,  0.35892349,  1.7969976 , -0.25398094],
       [ 0.43140327,  1.07638148, -0.89801104, -2.97617451],
       [ 0.50152535, -1.06255397,  0.37606069,  0.38831625]])

In [32]:
data[data<0] =0
data


array([[0.20253616, 1.65547602, 0.62553916, 0.12100184],
       [0.38005663, 0.71606429, 0.73144474, 1.58502893],
       [0.6164023 , 0.55275653, 0.14077322, 0.97602014],
       [0.        , 0.        , 0.        , 0.        ],
       [0.73513988, 0.35892349, 1.7969976 , 0.        ],
       [0.43140327, 1.07638148, 0.        , 0.        ],
       [0.50152535, 0.        , 0.37606069, 0.38831625]])