<a href="https://colab.research.google.com/github/arasulo/arasulo/blob/main/Copy_of_birinchi_nbk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 100, 10)
arr [-2]

80

In [ ]:
arr[3:5]

array([40, 50])

In [ ]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr = arr[3:5] 
sliced_arr [:] = 0
sliced_arr

array([0, 0])

In [ ]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

In [ ]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr1 = np.arange(10, 100, 10)
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
sliced_arr1 = arr1[3:5].copy
sliced_arr1[:] = 0
sliced_arr1

TypeError: ignored

In [ ]:
print ( " salom, mohirdev " )

 salom, mohirdev 


#*Heading*

In [ ]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import tensorflow as tf
import keras

In [ ]:
import torch
torch.cuda.is_available()

True